# Python for Data Analytis

# PANDAS LEARNING (PART - 01)

## What is Pandas?

Pandas is an open-source Python library used for data manipulation, cleaning, analysis, and visualization. It provides powerful data structures like **Series** and **DataFrame**.

## Why Pandas?

- Easy data manipulation
- Data cleaning & preprocessing
- Fast data analysis
- Read/Write CSV, Excel, JSON, SQL
- Data Analytics & Machine Learning

## Features

- Series
- DataFrame
- Data Import & Export
- Data Cleaning
- Data Filtering
- Sorting
- GroupBy Operations
- Merge & Join
- Missing Value Handling
- Statistical Analysis

## Common Functions

- `pd.Series()` – Create Series
- `pd.DataFrame()` – Create DataFrame
- `pd.read_csv()` – Read CSV File
- `pd.read_excel()` – Read Excel File
- `df.head()` – First 5 Rows
- `df.tail()` – Last 5 Rows
- `df.info()` – Dataset Information
- `df.describe()` – Statistical Summary
- `df.shape` – Dataset Shape
- `df.columns` – Column Names
- `df.isnull()` – Check Missing Values
- `df.fillna()` – Fill Missing Values
- `df.dropna()` – Remove Missing Values
- `df.groupby()` – Group Data
- `df.sort_values()` – Sort Data
- `df.merge()` – Merge DataFrames

## Applications

- Data Cleaning
- Data Analysis
- Data Visualization
- Business Intelligence
- Machine Learning

# SERIES (pd.Series)

In [1]:
## Pandas Series : It is a one-dimensional labeled array that can store data of any type (integers, strings, floats, etc.). Each value in a Series is associated with an index, making data easy to access and manipulate.


import pandas as pd
data=[10,20,30,40,50]
series=pd.Series(data)
print("Series:\n", series)
print(type(series))

Series:
 0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

In [2]:
data={1:'Shivam', 2:'Apoorva', 3:'Tanu', 4:'Sahil'}
dict_series=pd.Series(data)
print("DICT_SERIES:\n", dict_series)

DICT_SERIES:
 1     Shivam
2    Apoorva
3       Tanu
4      Sahil
dtype: object

In [3]:
data= ['Shivam','Sammy','Sam','Tanu','Apoorva','Appu','Sahil','Ishan']
index=[1,2,3,4,5,6,7,8]
series=pd.Series(data,index=index)
print("NAMING_SERIES: \n", series)

NAMING_SERIES:
 1     Shivam
2      Sammy
3        Sam
4       Tanu
5    Apoorva
6       Appu
7      Sahil
8      Ishan
dtype: object

# DATA FRAME (df=pd.DataFrame)

In [4]:
## Creating a data frame from Dict....

data={
    'Name':['Shivam','Apoorva','Sahil'],
    'Age':[21, 19, 20],
    'Domain':['Data Analyst', 'Frontend','Java Developer' ],
    'City':['Gorakhpur', 'Kotdwar', 'Kanpur']
}
df01=pd.DataFrame(data)
print("DATA TABLE:\n",df01)
print(type(df01))

DATA TABLE:
       Name  Age          Domain       City
0   Shivam   21    Data Analyst  Gorakhpur
1  Apoorva   19        Frontend    Kotdwar
2    Sahil   20  Java Developer     Kanpur
<class 'pandas.core.frame.DataFrame'>

In [5]:
## Creating a data frame from list of  Dict....

data02=[
    {'Name':'Shivam','Age':21,'Domain':'Data Analyst','City':'Gorakhpur'},
    {'Name':'Apoorva','Age':19,'Domain':'Frontend','City':'Kotdwar'},
    {'Name':'Sahil','Age':20,'Domain':'Java Developer','City':'Kanpur'}
]
df02=pd.DataFrame(data)
print("DATA TABLE:\n",df02)
print(type(df02))

DATA TABLE:
       Name  Age          Domain       City
0   Shivam   21    Data Analyst  Gorakhpur
1  Apoorva   19        Frontend    Kotdwar
2    Sahil   20  Java Developer     Kanpur
<class 'pandas.core.frame.DataFrame'>

In [6]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [7]:
df.tail(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
995,1010,2023-04-15,Charlie,North,4733.88,4,Food,4943.03,5442.15,Returning,0.29,Cash,Online,North-Charlie
996,1067,2023-09-07,Bob,North,4716.36,37,Clothing,1754.32,1856.40,New,0.21,Bank Transfer,Retail,North-Bob
997,1018,2023-04-27,David,South,7629.70,17,Clothing,355.72,438.27,Returning,0.06,Bank Transfer,Online,South-David
998,1100,2023-12-20,David,West,1629.47,39,Electronics,3685.03,3743.39,New,0.01,Bank Transfer,Online,West-David
999,1086,2023-08-16,Alice,East,4923.93,48,Food,2632.58,2926.68,Returning,0.14,Cash,Online,East-Alice

In [8]:
## Acessing DATA from Data Frame
data

{'Name': ['Shivam', 'Apoorva', 'Sahil'],
 'Age': [21, 19, 20],
 'Domain': ['Data Analyst', 'Frontend', 'Java Developer'],
 'City': ['Gorakhpur', 'Kotdwar', 'Kanpur']}

In [9]:
df01 ##ROW Wsie Data

      Name  Age          Domain       City
0   Shivam   21    Data Analyst  Gorakhpur
1  Apoorva   19        Frontend    Kotdwar
2    Sahil   20  Java Developer     Kanpur

In [10]:
df01['Name']

0     Shivam
1    Apoorva
2      Sahil
Name: Name, dtype: object

In [11]:
df01.loc[1]

Name       Apoorva
Age             19
Domain    Frontend
City       Kotdwar
Name: 1, dtype: object

In [12]:
df01.loc[0][1]

C:\Users\itzra\AppData\Local\Temp\ipykernel_9140\1524106411.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df01.loc[0][1]

np.int64(21)

In [13]:
 df01.iloc[0][0]

C:\Users\itzra\AppData\Local\Temp\ipykernel_9140\1894650084.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df01.iloc[0][0]

'Shivam'

In [14]:
## Acessing a Specific Element

df01.at[1,'Name']
df01.at[2,'Age']

np.int64(20)

In [15]:
## Acessing Specified Element usijng (iat)

df01.iat[1,3]

'Kotdwar'

In [16]:
df01

      Name  Age          Domain       City
0   Shivam   21    Data Analyst  Gorakhpur
1  Apoorva   19        Frontend    Kotdwar
2    Sahil   20  Java Developer     Kanpur

In [17]:
## Data Manupulation With Data Frame


#01- Adding the column

df01['State']=['Uttar Pradesh','Uttarakhand','Uttar Pradesh']
df01

      Name  Age          Domain       City          State
0   Shivam   21    Data Analyst  Gorakhpur  Uttar Pradesh
1  Apoorva   19        Frontend    Kotdwar    Uttarakhand
2    Sahil   20  Java Developer     Kanpur  Uttar Pradesh

In [18]:
#01- Remove the column
df01.drop('City', axis=1) ## Temprorily Removve the Column

      Name  Age          Domain          State
0   Shivam   21    Data Analyst  Uttar Pradesh
1  Apoorva   19        Frontend    Uttarakhand
2    Sahil   20  Java Developer  Uttar Pradesh

In [19]:
df01.drop('City', axis=1,  inplace=True) ## To Remove Permanent Cpolumn

In [20]:
df01

      Name  Age          Domain          State
0   Shivam   21    Data Analyst  Uttar Pradesh
1  Apoorva   19        Frontend    Uttarakhand
2    Sahil   20  Java Developer  Uttar Pradesh

In [21]:
## Perfoming Arthemetic Opertion on the Data Frame  
df01['Age']=df01['Age']+1
df01

      Name  Age          Domain          State
0   Shivam   22    Data Analyst  Uttar Pradesh
1  Apoorva   20        Frontend    Uttarakhand
2    Sahil   21  Java Developer  Uttar Pradesh

In [22]:
df01.drop(2)

      Name  Age        Domain          State
0   Shivam   22  Data Analyst  Uttar Pradesh
1  Apoorva   20      Frontend    Uttarakhand

In [23]:
df01.drop(2, inplace=True)

In [24]:
df01

      Name  Age        Domain          State
0   Shivam   22  Data Analyst  Uttar Pradesh
1  Apoorva   20      Frontend    Uttarakhand

In [25]:
## Some Other Operation On the Data Frame 

#01- DATA TYPE (df.dtypes)
#02- STATAICAL SUMMARY (df.decribe())

In [26]:
df.head(5)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob
2,1015,2023-09-21,David,South,4631.23,30,Food,261.56,371.40,Returning,0.20,Bank Transfer,Retail,South-David
3,1072,2023-08-24,Bob,South,2167.94,39,Clothing,4330.03,4467.75,New,0.02,Credit Card,Retail,South-Bob
4,1061,2023-03-24,Charlie,East,3750.20,13,Electronics,637.37,692.71,New,0.08,Credit Card,Online,East-Charlie

In [27]:
print("Statical Summary: \n", df.describe())

Statical Summary:
         Product_ID  Sales_Amount  Quantity_Sold    Unit_Cost   Unit_Price  \
count  1000.000000   1000.000000    1000.000000  1000.000000  1000.000000
mean   1050.128000   5019.265230      25.355000  2475.304550  2728.440120
std      29.573505   2846.790126      14.159006  1417.872546  1419.399839
min    1001.000000    100.120000       1.000000    60.280000   167.120000
25%    1024.000000   2550.297500      13.000000  1238.380000  1509.085000
50%    1051.000000   5019.300000      25.000000  2467.235000  2696.400000
75%    1075.000000   7507.445000      38.000000  3702.865000  3957.970000
max    1100.000000   9989.040000      49.000000  4995.300000  5442.150000

         Discount
count  1000.00000
mean      0.15239
std       0.08720
min       0.00000
25%       0.08000
50%       0.15000
75%       0.23000
max       0.30000

In [28]:
df.describe()

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1050.128000,5019.265230,25.355000,2475.304550,2728.440120,0.15239
std,29.573505,2846.790126,14.159006,1417.872546,1419.399839,0.08720
min,1001.000000,100.120000,1.000000,60.280000,167.120000,0.00000
25%,1024.000000,2550.297500,13.000000,1238.380000,1509.085000,0.08000
50%,1051.000000,5019.300000,25.000000,2467.235000,2696.400000,0.15000
75%,1075.000000,7507.445000,38.000000,3702.865000,3957.970000,0.23000
max,1100.000000,9989.040000,49.000000,4995.300000,5442.150000,0.30000

In [29]:
df.dtypes

Product_ID                int64
Sale_Date                object
Sales_Rep                object
Region                   object
Sales_Amount            float64
Quantity_Sold             int64
Product_Category         object
Unit_Cost               float64
Unit_Price              float64
Customer_Type            object
Discount                float64
Payment_Method           object
Sales_Channel            object
Region_and_Sales_Rep     object
dtype: object

# PANDAS LEARNING (PART - 02)

In [30]:
import pandas as pd

In [31]:
df=pd.read_csv('layoffs.csv')
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

In [32]:
## Handeling Missing & null Value

df.isnull()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False
3,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2356,False,False,False,False,False,True,False,False,True
2357,False,False,False,False,False,False,False,False,False
2358,False,False,False,False,False,False,False,False,False
2359,False,False,False,True,True,False,False,False,False
2360,False,False,False,False,False,False,False,False,False

In [33]:
df.isnull().any(axis=1)

0       False
1       False
2        True
3        True
4       False
        ...
2356     True
2357    False
2358    False
2359     True
2360    False
Length: 2361, dtype: bool

In [34]:
df.isnull().sum()

company                    0
location                   0
industry                   4
total_laid_off           740
percentage_laid_off      785
date                       1
stage                      6
country                    0
funds_raised_millions    209
dtype: int64

In [35]:
df.fillna(0)

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0
2,Alerzo,Ibadan,Retail,400.0,0.00,3/6/2023,Series B,Nigeria,16.0
3,UpGrad,Mumbai,Education,120.0,0.00,3/6/2023,Unknown,India,631.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0
...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500.0,0.14,0,Post-IPO,United States,0.0
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0
2359,Casper,New York City,Retail,0.0,0.00,9/14/2021,Post-IPO,United States,339.0
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0

In [36]:
## Filling Missing Values with the mean of the column
df=pd.read_csv('layoffs.csv')
df['total_laid_off_fillNA']= df['total_laid_off'].fillna(df['total_laid_off'].mean())
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions,total_laid_off_fillNA
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0,500.000000
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0,475.000000
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0,400.000000
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0,120.000000
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0,340.000000
...,...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN,500.000000
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0,1600.000000
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0,70.000000
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0,238.358421
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0,300.000000

In [37]:
df.describe()

,total_laid_off,percentage_laid_off,funds_raised_millions,total_laid_off_fillNA
count,1621.000000,1576.000000,2152.000000,2361.000000
mean,238.358421,0.257917,822.454134,238.358421
std,769.718801,0.255575,5593.961626,637.725232
min,3.000000,0.000000,0.000000,3.000000
25%,36.000000,0.100000,50.000000,50.000000
50%,80.000000,0.170000,156.500000,154.000000
75%,180.000000,0.300000,445.000000,238.358421
max,12000.000000,1.000000,121900.000000,12000.000000

In [38]:
df

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions,total_laid_off_fillNA
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0,500.000000
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0,475.000000
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0,400.000000
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0,120.000000
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0,340.000000
...,...,...,...,...,...,...,...,...,...,...
2356,Blackbaud,Charleston,Other,500.0,0.14,NaN,Post-IPO,United States,NaN,500.000000
2357,Yahoo,SF Bay Area,Consumer,1600.0,0.20,2/9/2023,Acquired,United States,6.0,1600.000000
2358,Hibob,Tel Aviv,HR,70.0,0.30,3/30/2020,Series A,Israel,45.0,70.000000
2359,Casper,New York City,Retail,NaN,NaN,9/14/2021,Post-IPO,United States,339.0,238.358421
2360,Wildlife Studios,Sao Paulo,Consumer,300.0,0.20,11/28/2022,Unknown,Brazil,260.0,300.000000

In [39]:
df.dtypes

company                   object
location                  object
industry                  object
total_laid_off           float64
percentage_laid_off      float64
date                      object
stage                     object
country                   object
funds_raised_millions    float64
total_laid_off_fillNA    float64
dtype: object

In [40]:
## Rename the Column Name-----

df=df.rename(columns={'Sales Date':'Layoff Date'})
df.head(5)
df=df.rename(columns={'total_laid_off_fillNA':'TLO'})
df.head(5)

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions,TLO
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0,500.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0,475.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0,400.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0,120.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0,340.0

In [41]:
## Changing the Data Type of the Column

df['total_laid_off_NEW']=df['TLO'].astype(int)
df.head(5)

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions,TLO,total_laid_off_NEW
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0,500.0,500
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0,475.0,475
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0,400.0,400
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0,120.0,120
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0,340.0,340

In [42]:
## Using Lambda Function 

df['Lambda_fn_Value']=df['TLO'].apply(lambda x:x*2)
df.head()

,company,location,industry,total_laid_off,percentage_laid_off,date,stage,country,funds_raised_millions,TLO,total_laid_off_NEW,Lambda_fn_Value
0,Atlassian,Sydney,Other,500.0,0.05,3/6/2023,Post-IPO,Australia,210.0,500.0,500,1000.0
1,SiriusXM,New York City,Media,475.0,0.08,3/6/2023,Post-IPO,United States,525.0,475.0,475,950.0
2,Alerzo,Ibadan,Retail,400.0,NaN,3/6/2023,Series B,Nigeria,16.0,400.0,400,800.0
3,UpGrad,Mumbai,Education,120.0,NaN,3/6/2023,Unknown,India,631.0,120.0,120,240.0
4,Loft,Sao Paulo,Real Estate,340.0,0.15,3/3/2023,Unknown,Brazil,788.0,340.0,340,680.0

In [43]:
 ## Data Aggregating and Grouping
Comapany_Mean=df.groupby('industry')['TLO'].mean()
print(Comapany_Mean)

industry
Aerospace          189.619474
Construction       315.924506
Consumer           458.229755
Crypto             203.205423
Crypto Currency    140.179210
CryptoCurrency      68.000000
Data               152.498661
Education          210.057193
Energy             186.012544
Fin-Tech            71.666667
Finance            170.303195
Fitness            359.083362
Food               241.545005
HR                 129.903062
Hardware           911.559350
Healthcare         223.877489
Infrastructure     245.399265
Legal              119.313482
Logistics          163.959549
Manufacturing      129.179210
Marketing          135.531677
Media              132.874853
Other              373.697062
Product            110.141218
Real Estate        233.655515
Recruiting         141.671147
Retail             300.664515
Sales              376.515548
Security           138.776373
Support            148.448862
Transportation     279.013368
Travel             328.148636
Name: TLO, dtype: float64

In [44]:
Country_wise_industry=df.groupby(['industry','country'])['TLO'].agg(['mean'])
(Country_wise_industry)

                                    mean
industry     country
Aerospace    United Kingdom   451.000000
             United States    137.343368
Construction Australia        238.358421
             Canada            97.666667
             Colombia         100.000000
...                                  ...
Travel       Myanmar          200.000000
             Netherlands     4375.000000
             Singapore        658.905614
             United Kingdom   149.800000
             United States    264.546594

[305 rows x 1 columns]

In [45]:
## MUltiple Aggregation fn :
AGG_VALUE=df.groupby('industry')['TLO'].agg(['sum','mean','min','max','count']).astype(int)
AGG_VALUE

                   sum  mean  min    max  count
industry
Aerospace         1137   189   40    451      6
Construction      5054   315   13   2434     16
Consumer         54071   458    5  12000    118
Crypto           20117   203    9   2000     99
Crypto Currency    280   140   42    238      2
CryptoCurrency      68    68   68     68      1
Data             12047   152   10    960     79
Education        19535   210    4   2500     93
Energy            2232   186   30    450     12
Fin-Tech           215    71   20    125      3
Finance          48366   170    5   2000    284
Fitness          11131   359   17   2800     31
Food             34057   241    4   1877    141
HR                8573   129    5    525     66
Hardware         15496   911   30   6650     17
Healthcare       40969   223    8   6000    183
Infrastructure   10552   245    6   4100     43
Legal             1551   119   24    238     13
Logistics         6886   163   10    640     42
Manufacturing      258   129   20    238      2
Marketing        18838   135    4   1500    139
Media            12623   132    5    600     95
Other            48206   373    8  10000    129
Product           3854   110    6    254     35
Real Estate      27337   233   11   3000    117
Recruiting        3966   141    7    960     28
Retail           58629   300    3  10000    195
Sales            13931   376   11   8000     37
Security         10269   138   13    950     74
Support           6383   148   16    700     43
Transportation   41293   279    7   3700    148
Travel           21657   328   10   4375     66

In [46]:
## Merging Data Frame


data1 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva","Sam"],
    "Age": [24, 27, 22, 32, 29, 21],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Miami","GKP,UP"]
}
data2 = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva","Appu"],
    "Gender": ["Female", "Male", "Male", "Male", "Female","Female"],
    "Salary": [50000, 60000, 55000, 70000, 65000,100000]
}

# Convert Dictionaries to DataFrames
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print(df1)
print()
print(df2)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eva   29        Miami
5      Sam   21       GKP,UP

      Name  Gender  Salary
0    Alice  Female   50000
1      Bob    Male   60000
2  Charlie    Male   55000
3    David    Male   70000
4      Eva  Female   65000
5     Appu  Female  100000

In [47]:
Inner_TABLE=pd.merge(df1,df2,on="Name",how="inner")
Inner_TABLE

      Name  Age         City  Gender  Salary
0    Alice   24     New York  Female   50000
1      Bob   27  Los Angeles    Male   60000
2  Charlie   22      Chicago    Male   55000
3    David   32      Houston    Male   70000
4      Eva   29        Miami  Female   65000

In [48]:
Outer_TABLE=pd.merge(df1,df2,on="Name",how="outer")
Outer_TABLE

      Name   Age         City  Gender    Salary
0    Alice  24.0     New York  Female   50000.0
1     Appu   NaN          NaN  Female  100000.0
2      Bob  27.0  Los Angeles    Male   60000.0
3  Charlie  22.0      Chicago    Male   55000.0
4    David  32.0      Houston    Male   70000.0
5      Eva  29.0        Miami  Female   65000.0
6      Sam  21.0       GKP,UP     NaN       NaN

In [49]:
Left_Outer_TABLE=pd.merge(df1,df2,on="Name",how="left")
Left_Outer_TABLE

      Name  Age         City  Gender   Salary
0    Alice   24     New York  Female  50000.0
1      Bob   27  Los Angeles    Male  60000.0
2  Charlie   22      Chicago    Male  55000.0
3    David   32      Houston    Male  70000.0
4      Eva   29        Miami  Female  65000.0
5      Sam   21       GKP,UP     NaN      NaN

In [50]:
Right_Outer_TABLE=pd.merge(df1,df2,on="Name",how="right")
Right_Outer_TABLE

      Name   Age         City  Gender  Salary
0    Alice  24.0     New York  Female   50000
1      Bob  27.0  Los Angeles    Male   60000
2  Charlie  22.0      Chicago    Male   55000
3    David  32.0      Houston    Male   70000
4      Eva  29.0        Miami  Female   65000
5     Appu   NaN          NaN  Female  100000

# Reading Data from Different Sources 
# PANDAS

In [51]:
import pandas as pd

In [52]:
## Reading Data From Json File

URL_df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)
URL_df.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
5,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
6,1,14.39,1.87,2.45,14.6,96,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290
7,1,14.06,2.15,2.61,17.6,121,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295
8,1,14.83,1.64,2.17,14.0,97,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045
9,1,13.86,1.35,2.27,16.0,98,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045

In [53]:
##JSON to CSV 

URL_df.to_csv("URL_data.csv")

In [54]:
## Reading Data FRom Url (HTML Formate)

url="https://www.fdic.gov/bank-failures/failed-bank-list"
HTML_df=pd.read_html(url)

In [55]:
html_df=HTML_df[0]

In [56]:
html_df

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
1,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
2,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
3,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
4,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
5,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
6,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
7,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
8,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
9,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
10,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
11,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
12,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
13,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
14,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
15,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
16,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
17,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
18,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
19,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
20,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
21,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
22,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
23,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
24,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526

In [57]:
html_df.to_csv("HTML_df.csv")

In [58]:
url="https://www.iban.com/dialing-codes"
URL_df=pd.read_html(url,match="Country",header=0)

In [59]:
Code=URL_df[0]

In [60]:
Code

,Country,Country Code,International Prefix,National Prefix,National Number,UTC/DST*,Note
0,Afghanistan,93,00,0,9 digits,+4.30,NaN
1,Albania,355,00,0,3 to 9 digits,+1/+2,NaN
2,Algeria,213,00,0,"8, 9 digits",+1,NaN
3,American Samoa,1,011,1,(684)+7 digits,-11,NaN
4,Andorra,376,00,...,"6, 8, 9 digits",+1/+2,NaN
...,...,...,...,...,...,...,...
239,Wallis and Futuna,681,00,...,6 digits,+12,NaN
240,Yemen,967,00,0,6 to 9 digits,+3,NaN
241,Zambia,260,00,0,9 digits,+2,NaN
242,Zimbabwe,263,00,0,5 to 10 digits,+2,NaN
243,Reserved,970,NaN,NaN,NaN,NaN,13.0

In [61]:
## Reading the Excle file

SWL_xl=pd.read_excel('SWL2026_Sports_Master_Sheet.xlsx')

In [62]:
SWL_xl.head(2)

,SPORTS,Faculty Name,Phone,Coordinator,Volunteer 1,Volunteer 2,Volunteer 3,Volunteer 4,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Volleyball,Mr. Deepesh Rajput,9958130804,SHUBHANSHU,Satwik,Shivam,Amar,NaN,NaN,NaN,NaN
1,NaN,Mr. Hemanshu Gautam,9045484116,8810453221,7398204701,9580522705,7983968893,NaN,NaN,NaN,NaN

#  Pandas Data Reading Functions

Pandas supports reading data from multiple file formats and data sources.

| Function | Description | Returns |
|----------|-------------|---------|
| `pd.read_csv()` | Read CSV (Comma-Separated Values) file | DataFrame |
| `pd.read_excel()` | Read Excel (.xlsx, .xls) file | DataFrame |
| `pd.read_json()` | Read JSON file | DataFrame |
| `pd.read_html()` | Read HTML tables from a webpage | List of DataFrames |
| `pd.read_sql()` | Read data from SQL query/database | DataFrame |
| `pd.read_sql_query()` | Read SQL query result | DataFrame |
| `pd.read_sql_table()` | Read an entire SQL table | DataFrame |
| `pd.read_xml()` | Read XML file | DataFrame |
| `pd.read_parquet()` | Read Parquet file | DataFrame |
| `pd.read_feather()` | Read Feather file | DataFrame |
| `pd.read_pickle()` | Read Pickle file | Object/DataFrame |
| `pd.read_hdf()` | Read HDF5 file | DataFrame |
| `pd.read_orc()` | Read ORC file | DataFrame |
| `pd.read_sas()` | Read SAS dataset | DataFrame |
| `pd.read_spss()` | Read SPSS (.sav) file | DataFrame |
| `pd.read_stata()` | Read Stata (.dta) file | DataFrame |
| `pd.read_fwf()` | Read Fixed Width Format file | DataFrame |
| `pd.read_table()` | Read Tab-separated (.txt/.tsv) file | DataFrame |

---

## Example Usage

### CSV

```python
df = pd.read_csv("employees.csv")
```

### Excel

```python
df = pd.read_excel("employees.xlsx")
```

### JSON

```python
df = pd.read_json("employees.json")
```

### HTML

```python
tables = pd.read_html(url)
df = tables[0]
```

### SQL

```python
df = pd.read_sql("SELECT * FROM employees", connection)
```

### XML

```python
df = pd.read_xml("employees.xml")
```

### Parquet

```python
df = pd.read_parquet("employees.parquet")
```

### Feather

```python
df = pd.read_feather("employees.feather")
```

### Pickle

```python
df = pd.read_pickle("employees.pkl")
```

### HDF5

```python
df = pd.read_hdf("employees.h5")
```

### ORC

```python
df = pd.read_orc("employees.orc")
```

### SAS

```python
df = pd.read_sas("employees.sas7bdat")
```

### SPSS

```python
df = pd.read_spss("employees.sav")
```

### Stata

```python
df = pd.read_stata("employees.dta")
```

### Fixed Width File

```python
df = pd.read_fwf("employees.txt")
```

### Tab Separated File

```python
df = pd.read_table("employees.tsv")
```

---

##  Tip

- `read_csv()` → CSV files
- `read_excel()` → Excel files
- `read_json()` → JSON files
- `read_html()` → Returns **List of DataFrames**
- `read_sql()` → Database
- `read_xml()` → XML data
- `read_parquet()` → Big Data / Analytics
- `read_pickle()` → Serialized Python objects